/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package window;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author C�lisons
 */
public class NewOrder extends JFrame {
    
     private JButton sendOrderButton = new JButton("Send Order");
     private JPanel jPanelNorth = new JPanel();
     private int service;
     private JTextField noteTextField = new JTextField();

    /**
     * Creates new form NewOrder
     * @param service
     */
    public NewOrder(int service) {
        initComponents();
        this.service = service;
        this.setTitle("New Order");
        this.setSize(410,410);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        sendOrderButton.addActionListener(new NewOrder.EnabledButton());
        sendOrderButton.setEnabled(true);
        noteTextField.setPreferredSize(new Dimension(20,50));
        
        jPanelNorth.add(sendOrderButton, BorderLayout.NORTH);
        //jPanelNorth.add(noteTextField, BorderLayout.CENTER);
        this.getContentPane().add(jPanelNorth, BorderLayout.NORTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class EnabledButton implements ActionListener {

        public void actionPerformed(ActionEvent aActionEvent){
            if (aActionEvent.getSource() == sendOrderButton){
                
            }
    }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
